Repository Activiti/activiti-cloud-api, pull requests merged in 2018-11, with the labels that each got.

#22 update org.activiti.api:activiti-api-dependencies to 7.0.37
  pom.xml
Labels: updatebot

#24 update org.activiti.api:activiti-api-dependencies to 7.0.38
  pom.xml
Labels: updatebot

#25 update org.activiti.api:activiti-api-dependencies to 7.0.39
  pom.xml
Labels: updatebot

#28 Create .mergify.yml
  .mergify.yml
Labels: enhancement, in progress

#32 update org.activiti.cloud.build:activiti-cloud-parent to 7.0.35
  pom.xml
Labels: in progress, updatebot

#30 fix: Id of an entity is used for entityId instead of processInstanceId
  activiti-cloud-api-process-model-impl/src/main/java/org/activiti/cloud/api/process/model/impl/CloudProcessInstanceImpl.java
  activiti-cloud-api-process-model-impl/src/main/java/org/activiti/cloud/api/process/model/impl/events/CloudBPMNActivityEventImpl.java
  activiti-cloud-api-process-model-impl/src/main/java/org/activiti/cloud/api/process/model/impl/events/CloudIntegrationRequestedImpl.java
  activiti-cloud-api-process-model-impl/src/main/java/org/activiti/cloud/api/process/model/impl/events/CloudIntegrationResultReceivedImpl.java
  activiti-cloud-api-process-model-impl/src/main/java/org/activiti/cloud/api/process/model/impl/events/CloudSequenceFlowTakenImpl.java
  activiti-cloud-api-process-model/src/main/java/org/activiti/cloud/api/process/model/events/CloudSequenceFlowEvent.java
  pom.xml
Labels: in progress

#29 Add process deployed event to the API
  activiti-cloud-api-process-model-impl/src/main/java/org/activiti/cloud/api/process/model/impl/conf/CloudProcessModelAutoConfiguration.java
  activiti-cloud-api-process-model-impl/src/main/java/org/activiti/cloud/api/process/model/impl/events/CloudProcessDeployedEventImpl.java
  activiti-cloud-api-process-model/src/main/java/org/activiti/cloud/api/process/model/events/CloudProcessDeployedEvent.java
Labels: in progress

#33 Configure Updatebot single PR for cloud-dependencies tests and automatic merge with Mergify
  .mergify.yml
  .updatebot.yml
Labels: enhancement, in progress

#35 update org.activiti.cloud.build:activiti-cloud-parent to 7.0.36
  pom.xml
Labels: in progress, updatebot

#36 update org.activiti.dependencies:activiti-dependencies to 7.0.62
  pom.xml
Labels: in progress, updatebot

#38 fix: add activiti-cloud-api-dependencies-tests module
  .mergify.yml
  .updatebot.yml
  activiti-cloud-api-dependencies/pom.xml
  activiti-cloud-api-model-shared-impl/pom.xml
  activiti-cloud-api-model-shared/pom.xml
  activiti-cloud-api-process-model-impl/pom.xml
  activiti-cloud-api-process-model/pom.xml
  activiti-cloud-api-task-model-impl/pom.xml
  activiti-cloud-api-task-model/pom.xml
  dependencies-tests/pom.xml
  pom.xml
Labels: enhancement, in progress

#39 fix(versions): update Activiti/activiti-cloud-api versions
  pom.xml
Labels: in progress, updatebot

#37 feat: preparation for handling CloudProcessUpdatedEvent
  activiti-cloud-api-process-model-impl/src/main/java/org/activiti/cloud/api/process/model/impl/conf/CloudProcessModelAutoConfiguration.java
  activiti-cloud-api-process-model-impl/src/main/java/org/activiti/cloud/api/process/model/impl/events/CloudProcessUpdatedEventImpl.java
  activiti-cloud-api-process-model/src/main/java/org/activiti/cloud/api/process/model/events/CloudProcessUpdatedEvent.java
Labels: in progress
