Repository Activiti/activiti-cloud-api, pull requests merged in 2018-12, with the labels that each got.

#40 fix(versions): update Activiti/activiti-cloud-api versions
  pom.xml
Labels: in progress, updatebot

#41 fix(versions): update Activiti/activiti-cloud-api versions
  pom.xml
Labels: in progress, updatebot

#44 feat: cloud event message header keys names constants
  activiti-cloud-api-model-shared/src/main/java/org/activiti/cloud/api/model/shared/messages/CloudRuntimeEventsMessageHeaders.java
  activiti-cloud-api-model-shared/src/main/java/org/activiti/cloud/api/model/shared/messages/IntegrationContextMessageHeaders.java
Labels: enhancement, in progress, ready-for-review

#43 feat: process processDefinitionVersion implemented
  activiti-cloud-api-process-model-impl/src/main/java/org/activiti/cloud/api/process/model/impl/CloudProcessInstanceImpl.java
  pom.xml
Labels: in progress

#47 fix(versions): update Activiti/activiti-cloud-api versions
  pom.xml
Labels: updatebot
